/*
 * Weather & Alerts API
 * Read-heavy weather/forecast/alerts API — a classic \"tool\" style MCP server (an LLM assistant calling out for live external data) plus one write operation (subscribe) and one delete (unsubscribe) to exercise both GET-only tools and mutation tools in the same server. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.probestack.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CurrentWeather
 */
@JsonPropertyOrder({
  CurrentWeather.JSON_PROPERTY_LOCATION,
  CurrentWeather.JSON_PROPERTY_TEMPERATURE_C,
  CurrentWeather.JSON_PROPERTY_CONDITION,
  CurrentWeather.JSON_PROPERTY_WIND_SPEED_KPH,
  CurrentWeather.JSON_PROPERTY_HUMIDITY_PERCENT,
  CurrentWeather.JSON_PROPERTY_OBSERVED_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-21T06:27:09.379277030Z[GMT]", comments = "Generator version: 7.9.0")
public class CurrentWeather {
  public static final String JSON_PROPERTY_LOCATION = "location";
  private String location;

  public static final String JSON_PROPERTY_TEMPERATURE_C = "temperatureC";
  private BigDecimal temperatureC;

  public static final String JSON_PROPERTY_CONDITION = "condition";
  private String condition;

  public static final String JSON_PROPERTY_WIND_SPEED_KPH = "windSpeedKph";
  private BigDecimal windSpeedKph;

  public static final String JSON_PROPERTY_HUMIDITY_PERCENT = "humidityPercent";
  private Integer humidityPercent;

  public static final String JSON_PROPERTY_OBSERVED_AT = "observedAt";
  private OffsetDateTime observedAt;

  public CurrentWeather() {
  }

  public CurrentWeather location(String location) {
    
    this.location = location;
    return this;
  }

  /**
   * Get location
   * @return location
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocation() {
    return location;
  }


  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocation(String location) {
    this.location = location;
  }

  public CurrentWeather temperatureC(BigDecimal temperatureC) {
    
    this.temperatureC = temperatureC;
    return this;
  }

  /**
   * Get temperatureC
   * @return temperatureC
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEMPERATURE_C)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getTemperatureC() {
    return temperatureC;
  }


  @JsonProperty(JSON_PROPERTY_TEMPERATURE_C)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTemperatureC(BigDecimal temperatureC) {
    this.temperatureC = temperatureC;
  }

  public CurrentWeather condition(String condition) {
    
    this.condition = condition;
    return this;
  }

  /**
   * Get condition
   * @return condition
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONDITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCondition() {
    return condition;
  }


  @JsonProperty(JSON_PROPERTY_CONDITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCondition(String condition) {
    this.condition = condition;
  }

  public CurrentWeather windSpeedKph(BigDecimal windSpeedKph) {
    
    this.windSpeedKph = windSpeedKph;
    return this;
  }

  /**
   * Get windSpeedKph
   * @return windSpeedKph
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WIND_SPEED_KPH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getWindSpeedKph() {
    return windSpeedKph;
  }


  @JsonProperty(JSON_PROPERTY_WIND_SPEED_KPH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWindSpeedKph(BigDecimal windSpeedKph) {
    this.windSpeedKph = windSpeedKph;
  }

  public CurrentWeather humidityPercent(Integer humidityPercent) {
    
    this.humidityPercent = humidityPercent;
    return this;
  }

  /**
   * Get humidityPercent
   * @return humidityPercent
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HUMIDITY_PERCENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getHumidityPercent() {
    return humidityPercent;
  }


  @JsonProperty(JSON_PROPERTY_HUMIDITY_PERCENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHumidityPercent(Integer humidityPercent) {
    this.humidityPercent = humidityPercent;
  }

  public CurrentWeather observedAt(OffsetDateTime observedAt) {
    
    this.observedAt = observedAt;
    return this;
  }

  /**
   * Get observedAt
   * @return observedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OBSERVED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getObservedAt() {
    return observedAt;
  }


  @JsonProperty(JSON_PROPERTY_OBSERVED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setObservedAt(OffsetDateTime observedAt) {
    this.observedAt = observedAt;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CurrentWeather currentWeather = (CurrentWeather) o;
    return Objects.equals(this.location, currentWeather.location) &&
        Objects.equals(this.temperatureC, currentWeather.temperatureC) &&
        Objects.equals(this.condition, currentWeather.condition) &&
        Objects.equals(this.windSpeedKph, currentWeather.windSpeedKph) &&
        Objects.equals(this.humidityPercent, currentWeather.humidityPercent) &&
        Objects.equals(this.observedAt, currentWeather.observedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(location, temperatureC, condition, windSpeedKph, humidityPercent, observedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CurrentWeather {\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    temperatureC: ").append(toIndentedString(temperatureC)).append("\n");
    sb.append("    condition: ").append(toIndentedString(condition)).append("\n");
    sb.append("    windSpeedKph: ").append(toIndentedString(windSpeedKph)).append("\n");
    sb.append("    humidityPercent: ").append(toIndentedString(humidityPercent)).append("\n");
    sb.append("    observedAt: ").append(toIndentedString(observedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

