/*
 * Weather & Alerts API
 * Read-heavy weather/forecast/alerts API — a classic \"tool\" style MCP server (an LLM assistant calling out for live external data) plus one write operation (subscribe) and one delete (unsubscribe) to exercise both GET-only tools and mutation tools in the same server. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.probestack.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.LocalDate;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ForecastDay
 */
@JsonPropertyOrder({
  ForecastDay.JSON_PROPERTY_DATE,
  ForecastDay.JSON_PROPERTY_HIGH_C,
  ForecastDay.JSON_PROPERTY_LOW_C,
  ForecastDay.JSON_PROPERTY_CONDITION,
  ForecastDay.JSON_PROPERTY_PRECIPITATION_CHANCE_PERCENT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-31T08:23:13.109827530Z[GMT]", comments = "Generator version: 7.9.0")
public class ForecastDay {
  public static final String JSON_PROPERTY_DATE = "date";
  private LocalDate date;

  public static final String JSON_PROPERTY_HIGH_C = "highC";
  private BigDecimal highC;

  public static final String JSON_PROPERTY_LOW_C = "lowC";
  private BigDecimal lowC;

  public static final String JSON_PROPERTY_CONDITION = "condition";
  private String condition;

  public static final String JSON_PROPERTY_PRECIPITATION_CHANCE_PERCENT = "precipitationChancePercent";
  private Integer precipitationChancePercent;

  public ForecastDay() {
  }

  public ForecastDay date(LocalDate date) {
    
    this.date = date;
    return this;
  }

  /**
   * Get date
   * @return date
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getDate() {
    return date;
  }


  @JsonProperty(JSON_PROPERTY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDate(LocalDate date) {
    this.date = date;
  }

  public ForecastDay highC(BigDecimal highC) {
    
    this.highC = highC;
    return this;
  }

  /**
   * Get highC
   * @return highC
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HIGH_C)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getHighC() {
    return highC;
  }


  @JsonProperty(JSON_PROPERTY_HIGH_C)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHighC(BigDecimal highC) {
    this.highC = highC;
  }

  public ForecastDay lowC(BigDecimal lowC) {
    
    this.lowC = lowC;
    return this;
  }

  /**
   * Get lowC
   * @return lowC
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOW_C)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getLowC() {
    return lowC;
  }


  @JsonProperty(JSON_PROPERTY_LOW_C)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLowC(BigDecimal lowC) {
    this.lowC = lowC;
  }

  public ForecastDay condition(String condition) {
    
    this.condition = condition;
    return this;
  }

  /**
   * Get condition
   * @return condition
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONDITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCondition() {
    return condition;
  }


  @JsonProperty(JSON_PROPERTY_CONDITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCondition(String condition) {
    this.condition = condition;
  }

  public ForecastDay precipitationChancePercent(Integer precipitationChancePercent) {
    
    this.precipitationChancePercent = precipitationChancePercent;
    return this;
  }

  /**
   * Get precipitationChancePercent
   * @return precipitationChancePercent
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRECIPITATION_CHANCE_PERCENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPrecipitationChancePercent() {
    return precipitationChancePercent;
  }


  @JsonProperty(JSON_PROPERTY_PRECIPITATION_CHANCE_PERCENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrecipitationChancePercent(Integer precipitationChancePercent) {
    this.precipitationChancePercent = precipitationChancePercent;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ForecastDay forecastDay = (ForecastDay) o;
    return Objects.equals(this.date, forecastDay.date) &&
        Objects.equals(this.highC, forecastDay.highC) &&
        Objects.equals(this.lowC, forecastDay.lowC) &&
        Objects.equals(this.condition, forecastDay.condition) &&
        Objects.equals(this.precipitationChancePercent, forecastDay.precipitationChancePercent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, highC, lowC, condition, precipitationChancePercent);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ForecastDay {\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    highC: ").append(toIndentedString(highC)).append("\n");
    sb.append("    lowC: ").append(toIndentedString(lowC)).append("\n");
    sb.append("    condition: ").append(toIndentedString(condition)).append("\n");
    sb.append("    precipitationChancePercent: ").append(toIndentedString(precipitationChancePercent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

