/*
 * Weather & Alerts API
 * Read-heavy weather/forecast/alerts API — a classic \"tool\" style MCP server (an LLM assistant calling out for live external data) plus one write operation (subscribe) and one delete (unsubscribe) to exercise both GET-only tools and mutation tools in the same server. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.probestack.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.probestack.sdk.model.ForecastDay;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetWeatherForecast200Response
 */
@JsonPropertyOrder({
  GetWeatherForecast200Response.JSON_PROPERTY_FORECAST_DAYS
})
@JsonTypeName("getWeatherForecast_200_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-31T08:35:58.204314211Z[GMT]", comments = "Generator version: 7.9.0")
public class GetWeatherForecast200Response {
  public static final String JSON_PROPERTY_FORECAST_DAYS = "forecastDays";
  private List<ForecastDay> forecastDays = new ArrayList<>();

  public GetWeatherForecast200Response() {
  }

  public GetWeatherForecast200Response forecastDays(List<ForecastDay> forecastDays) {
    
    this.forecastDays = forecastDays;
    return this;
  }

  public GetWeatherForecast200Response addForecastDaysItem(ForecastDay forecastDaysItem) {
    if (this.forecastDays == null) {
      this.forecastDays = new ArrayList<>();
    }
    this.forecastDays.add(forecastDaysItem);
    return this;
  }

  /**
   * Get forecastDays
   * @return forecastDays
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FORECAST_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ForecastDay> getForecastDays() {
    return forecastDays;
  }


  @JsonProperty(JSON_PROPERTY_FORECAST_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setForecastDays(List<ForecastDay> forecastDays) {
    this.forecastDays = forecastDays;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetWeatherForecast200Response getWeatherForecast200Response = (GetWeatherForecast200Response) o;
    return Objects.equals(this.forecastDays, getWeatherForecast200Response.forecastDays);
  }

  @Override
  public int hashCode() {
    return Objects.hash(forecastDays);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetWeatherForecast200Response {\n");
    sb.append("    forecastDays: ").append(toIndentedString(forecastDays)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

