/*
 * Weather & Alerts API
 * Read-heavy weather/forecast/alerts API — a classic \"tool\" style MCP server (an LLM assistant calling out for live external data) plus one write operation (subscribe) and one delete (unsubscribe) to exercise both GET-only tools and mutation tools in the same server. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.probestack.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SubscribeToAlertsRequest
 */
@JsonPropertyOrder({
  SubscribeToAlertsRequest.JSON_PROPERTY_EMAIL,
  SubscribeToAlertsRequest.JSON_PROPERTY_REGION,
  SubscribeToAlertsRequest.JSON_PROPERTY_MIN_SEVERITY
})
@JsonTypeName("subscribeToAlerts_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-21T06:27:09.379277030Z[GMT]", comments = "Generator version: 7.9.0")
public class SubscribeToAlertsRequest {
  public static final String JSON_PROPERTY_EMAIL = "email";
  private String email;

  public static final String JSON_PROPERTY_REGION = "region";
  private String region;

  /**
   * Only notify for alerts at or above this severity
   */
  public enum MinSeverityEnum {
    MINOR("MINOR"),
    
    MODERATE("MODERATE"),
    
    SEVERE("SEVERE"),
    
    EXTREME("EXTREME");

    private String value;

    MinSeverityEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static MinSeverityEnum fromValue(String value) {
      for (MinSeverityEnum b : MinSeverityEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }
  public static final String JSON_PROPERTY_MIN_SEVERITY = "minSeverity";
  private MinSeverityEnum minSeverity;

  public SubscribeToAlertsRequest() {
  }

  public SubscribeToAlertsRequest email(String email) {
    
    this.email = email;
    return this;
  }

  /**
   * Email address to notify
   * @return email
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEmail(String email) {
    this.email = email;
  }

  public SubscribeToAlertsRequest region(String region) {
    
    this.region = region;
    return this;
  }

  /**
   * Region name or code to watch
   * @return region
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REGION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRegion() {
    return region;
  }


  @JsonProperty(JSON_PROPERTY_REGION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRegion(String region) {
    this.region = region;
  }

  public SubscribeToAlertsRequest minSeverity(MinSeverityEnum minSeverity) {
    
    this.minSeverity = minSeverity;
    return this;
  }

  /**
   * Only notify for alerts at or above this severity
   * @return minSeverity
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MIN_SEVERITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MinSeverityEnum getMinSeverity() {
    return minSeverity;
  }


  @JsonProperty(JSON_PROPERTY_MIN_SEVERITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMinSeverity(MinSeverityEnum minSeverity) {
    this.minSeverity = minSeverity;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscribeToAlertsRequest subscribeToAlertsRequest = (SubscribeToAlertsRequest) o;
    return Objects.equals(this.email, subscribeToAlertsRequest.email) &&
        Objects.equals(this.region, subscribeToAlertsRequest.region) &&
        Objects.equals(this.minSeverity, subscribeToAlertsRequest.minSeverity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, region, minSeverity);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscribeToAlertsRequest {\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    minSeverity: ").append(toIndentedString(minSeverity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

