/*
 * Task Manager API
 * A simple task management API used to end-to-end test MCP generation (spec parse, tools, mock server, contract testing, code analysis).
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.probestack.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateTaskRequest
 */
class CreateTaskRequestTest {
    private final CreateTaskRequest model = new CreateTaskRequest();

    /**
     * Model tests for CreateTaskRequest
     */
    @Test
    void testCreateTaskRequest() {
        // TODO: test CreateTaskRequest
    }

    /**
     * Test the property 'title'
     */
    @Test
    void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'assignee'
     */
    @Test
    void assigneeTest() {
        // TODO: test assignee
    }

    /**
     * Test the property 'priority'
     */
    @Test
    void priorityTest() {
        // TODO: test priority
    }

    /**
     * Test the property 'dueDate'
     */
    @Test
    void dueDateTest() {
        // TODO: test dueDate
    }

}
