/*
 * Weather & Alerts API
 * Read-heavy weather/forecast/alerts API — a classic \"tool\" style MCP server (an LLM assistant calling out for live external data) plus one write operation (subscribe) and one delete (unsubscribe) to exercise both GET-only tools and mutation tools in the same server. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.probestack.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.LocalDate;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ForecastDay
 */
class ForecastDayTest {
    private final ForecastDay model = new ForecastDay();

    /**
     * Model tests for ForecastDay
     */
    @Test
    void testForecastDay() {
        // TODO: test ForecastDay
    }

    /**
     * Test the property 'date'
     */
    @Test
    void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'highC'
     */
    @Test
    void highCTest() {
        // TODO: test highC
    }

    /**
     * Test the property 'lowC'
     */
    @Test
    void lowCTest() {
        // TODO: test lowC
    }

    /**
     * Test the property 'condition'
     */
    @Test
    void conditionTest() {
        // TODO: test condition
    }

    /**
     * Test the property 'precipitationChancePercent'
     */
    @Test
    void precipitationChancePercentTest() {
        // TODO: test precipitationChancePercent
    }

}
